### ISSUE TITLE
Exporting a map doesn't work correctly

### ISSUE THREAD

**Issue by Bdtrotte** [Bdtrotte/3D-Map-Gen#27] opened 2018-02-02 18:15 UTC
With the current setup, the map seen in MeshView isn't what is exported as a model file

**Comment by wlwlw** [comment] 2018-02-03 01:44
This bug is caused by incorrect index. obj file index vertex from 1, while in program vertex is indexed from 0. I forgot that when saving the obj file...
Now fixed.

**Closed as completed by wlwlw** 2018-02-03 01:44 UTC
Labels: bug
